before_script:
  - apt update && apt install -y cmake python-pip python-dev
  - pip install conan
  - conan user

stages:
  - build

gcc-4:
  stage: build
  image: gcc:4
  script:
    - conan test_package --build=missing
  tags:
    - docker

gcc-5:
  stage: build
  image: gcc:5
  script:
    - conan test_package --build=missing
  tags:
    - docker

gcc-6:
  stage: build
  image: gcc:6
  script:
    - conan test_package --build=missing
  tags:
    - docker

clang-3.9:
  stage: build
  image: purplekarrot/clang-3.9
  script:
    - conan test_package --build=missing
  tags:
    - docker
