build:

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan

build_script:
  - conan test_package --build=missing -s build_type=%BUILD_TYPE% -s compiler="Visual Studio" -s compiler.version=%TOOLCHAIN_VERSION%

on_success:
  - conan user filonovpv -p %CONAN_PASSWORD% -r conan.io
  - conan copy hello/0.1@demo/testing filonovpv/testing --all
  - conan upload hello/0.1@filonovpv/testing -r conan.io --all

environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.8"
  PYTHON_ARCH: "32"
  matrix:
    - TOOLCHAIN_VERSION: 14
      BUILD_TYPE: Debug
    - TOOLCHAIN_VERSION: 12
      BUILD_TYPE: Debug
    - TOOLCHAIN_VERSION: 10
      BUILD_TYPE: Debug
    - TOOLCHAIN_VERSION: 14
      BUILD_TYPE: Release
    - TOOLCHAIN_VERSION: 12
      BUILD_TYPE: Release
    - TOOLCHAIN_VERSION: 10
      BUILD_TYPE: Release
